project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r"^", include("vozickarskenoviny.urls")),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vozickarskenoviny/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import TemplateView

from views import *

class TextTemplateView(TemplateView):
    def render_to_response(self, context, **response_kwargs):
        response_kwargs['content_type'] = 'text/plain'
        return super(TemplateView, self).render_to_response(context, **response_kwargs)


urlpatterns = patterns('',
    url('^markdown/', include( 'django_markdown.urls')),
    url(r'^robots.txt$', TextTemplateView.as_view(template_name="vozickarskenoviny/robots.txt")),
    url(r'^$',
        home_view,
        name="vn", ),
    url(r'^sekce/(?P<url_key>[a-zA-Z0-9-]+)/$',
        section_view,
        name="vn.section", ),
    url(r'^clanek/(?P<url_key>[a-zA-Z0-9-]+)/$',
        article_view,
        name="vn.article", ),
    url(r'^sitemap.xml$',
        sitemap_view,
        name="sitemap", ),
)

vozickarskenoviny/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class SectionManager(models.Manager):
    def all(self):
        return self.order_by('order', "name")

    def with_article(self):
        return filter(None, (section if section.article_set.all().count() > 0 else None for section in self.all()))


class Section(models.Model):
    objects = SectionManager()

    name = models.CharField(max_length=32)
    url_key = models.SlugField(max_length=32, blank=True, unique=True)

    order = models.IntegerField(default=1)

    def last_article(self):
        return self.article_set.last()

    def last_7_articles(self):
        return self.article_set.all()[:7]

    def last1(self):
        return self.article_set.last1()

    def __unicode__(self):
        return u"%s"%self.name

    def save(self, *args, **kwargs):
        if not self.url_key:
            self.url_key = slugify(self.name)
        super(Section, self).save(*args, **kwargs)

class Author(User):
    pass

class ArticleManager(models.Manager):
    def all(self):
        return self.filter(active=True, date_creation__lte=datetime.datetime.now()).order_by("-date_creation", "-pk")

    def last(self, i=0):
        try:
            return self.all()[i]
        except IndexError:
            return None

    def last1(self):
        return self.last(1)

    def popularity(self):
        return self.all().order_by("-reads", "-date_creation", "-pk")


class Article(models.Model):
    objects = ArticleManager()

    reads = models.IntegerField(default=0)
    date_creation = models.DateTimeField(default=datetime.datetime.now)
    date_actualization = models.DateTimeField(default=datetime.datetime.now)
    show_actualization = models.BooleanField()
    active = models.BooleanField()
    author = models.ForeignKey(Author)
    section = models.ForeignKey(Section)

    title = models.CharField(max_length=255)
    url_key = models.SlugField(blank=True, unique=True)
    perex = models.TextField()
    text1 = models.TextField()
    text2 = models.TextField()

    keywords = models.CharField(max_length=255)

    img = models.ImageField(upload_to="imgs")
    img_author = models.CharField(max_length=64, default='', blank=True)
    img_description = models.CharField(max_length=255, default='', blank=True)
    video = models.CharField(blank=True, null=True, help_text=u'YouTube video ID (e.g. f1U0beJtPPI)', max_length=16)

    img1 = models.ImageField(upload_to="imgs", blank=True, null=True)
    img1_author = models.CharField(max_length=64, default='', blank=True)
    img1_description = models.CharField(max_length=255, default='', blank=True)
    img2 = models.ImageField(upload_to="imgs", blank=True, null=True)
    img2_author = models.CharField(max_length=64, default='', blank=True)
    img2_description = models.CharField(max_length=255, default='', blank=True)
    img3 = models.ImageField(upload_to="imgs", blank=True, null=True)
    img3_author = models.CharField(max_length=64, default='', blank=True)
    img3_description = models.CharField(max_length=255, default='', blank=True)
    img4 = models.ImageField(upload_to="imgs", blank=True, null=True)
    img4_author = models.CharField(max_length=64, default='', blank=True)
    img4_description = models.CharField(max_length=255, default='', blank=True)
    img5 = models.ImageField(upload_to="imgs", blank=True, null=True)
    img5_author = models.CharField(max_length=64, default='', blank=True)
    img5_description = models.CharField(max_length=255, default='', blank=True)
    img6 = models.ImageField(upload_to="imgs", blank=True, null=True)
    img6_author = models.CharField(max_length=64, default='', blank=True)
    img6_description = models.CharField(max_length=255, default='', blank=True)

    def __unicode__(self):
        return u"(%i) (%s) %s" % (self.pk, self.author, self.title[:50])

    def get_related(self):
        return Article.objects.all().filter(section=self.section, active=True).exclude(pk=self.pk)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.url_key = slugify(self.title)
        self.date_actualization = datetime.datetime.now()
        return super(Article, self).save(*args, **kwargs)

    def get_comments(self):
        return self.comment_set.order_by("pk")

    class Meta:
        ordering = ('-date_creation', )


class Comment(models.Model):
    article = models.ForeignKey(Article)
    created_at = models.DateField(auto_now_add=True)

    author_name = models.CharField(max_length=64)
    author_email = models.CharField(max_length=64)

    title = models.CharField(max_length=255)
    text = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return u"%s %i %s" % (self.title[:30], self.pk, self.article.title)

vozickarskenoviny/forms.py
from django import forms

from django_markdown.widgets import MarkdownWidget

from models import Comment, Article


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author_name', 'author_email', 'title', 'text')

class ArticleAdminForm(forms.ModelForm):
    text1 = forms.CharField(widget=MarkdownWidget())
    text2 = forms.CharField(widget=MarkdownWidget())

    class Meta:
        model = Article

vozickarskenoviny/views.py
import datetime

from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.db.models import Sum

from models import Article, Section
from forms import CommentForm


def home_view(request, template="vozickarskenoviny/home.html"):
    last_from_section = Section.objects.with_article()
    for i in xrange(len(last_from_section)):
        last_from_section[i].last = last_from_section[i].last_article()
    last_from_section = zip(last_from_section[::2], last_from_section[1::2])

    reads_sum = Article.objects.all().aggregate(Sum('reads'))['reads__sum']
    return render_to_response(template,
        {
            "main_menu": Section.objects.with_article(),
            "popular3": Article.objects.popularity()[:3],

            'reads_sum': Article.objects.all().aggregate(Sum('reads'))['reads__sum'], 
            "last_from_section": last_from_section,
            "last": Article.objects.last(),
            "last3": Article.objects.all()[1:4],
        },
        context_instance=RequestContext(request))


def section_view(request, url_key, template="vozickarskenoviny/section.html"):
    section = Section.objects.get(url_key=url_key)
    articles = Article.objects.all().filter(section=section)
    return render_to_response(template,
        {
            'title': section.name,
            "main_menu": Section.objects.with_article(),
            'current_section': section,
            "popular3": Article.objects.popularity()[:3],

            "last": articles[0],
            "next": articles[1:],
        },
        context_instance=RequestContext(request))

def article_view(request, url_key, template="vozickarskenoviny/article.html"):
    article = get_object_or_404(Article, url_key=url_key, date_creation__lte=datetime.datetime.now())
    article.reads += 1
    article.save()

    comment_form = CommentForm(request.POST or None)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.save()
        return HttpResponseRedirect(reverse("vn.article", args=[article.url_key], ))

    return render_to_response(template,
        {
            'title': article.title,
            "main_menu": Section.objects.with_article(),
            "comment_form": comment_form,
            'current_section': article.section,
            "popular3": Article.objects.popularity()[:3],

            "article": article,
            "related1": article.get_related()[0:3],
            "related2": article.get_related()[4:7],
            "related3": article.get_related()[8:10],
        },
        context_instance=RequestContext(request))

def sitemap_view(request, template="vozickarskenoviny/sitemap.xml"):
    urls = ['/']
    for section in Section.objects.all():
        urls.append(reverse('vn.section', args=(section.url_key, )))
    for article in Article.objects.all():
        urls.append(reverse('vn.article', args=(article.url_key, )))
    return render_to_response(template,
        {
            "urls": urls,
        },
        content_type="text/xml",
        context_instance=RequestContext(request))

vozickarskenoviny/templates/vozickarskenoviny/article.html
{% extends "vozickarskenoviny/base.html"%}
{% load markup simple_ads %}
{% block base_content %}
<div class="row" style="margin-bottom:10px;">
            <div class="span7" style="">
                <div class="row" style="margin-bottom:10px;">
                    <div class="span7">
                        <h2>{{article.title}}</h2>
                    </div>
                </div>
                <div class="row" style="margin-bottom:10px;">
                    <div class="span7">
                        {% if article.video %}
                            <iframe width="640px" height="480px" src="https://www.youtube.com/embed/{{ article.video }}" frameborder="0" allowfullscreen></iframe>
                        {% else %}
                            <img src="{{article.img.url}}">
                        {% endif %}
                        {% if article.img_description or article.img_author %}
                            <p style="font-size: 0.8em">
                                {{article.img_description}} {{article.img_author}}
                            </p>
                        {% endif %}
                        <p style="font-size: 0.7em">
                            {% if article.show_actualization %}
                                Poslední aktualizace:
                            {% else %}
                                Publikováno:
                            {% endif %}
                            {% if article.show_actualization %}
                                {{ article.date_actualization }}
                            {% else %}
                                {{ article.date_creation }}
                            {% endif %}
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="span2">
                        {% random_ad_by_size '170x400' %}
                        <div style="height: 10px;"></div>
                        {% random_ad_by_size '170x170' %}
                    </div>
                    <div class="span5">
                        <div class="row" style="margin-bottom:10px;">
                            <div class="span5">
                                <p style="text-align: justify;" class="perex">{{article.perex}}</p>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom:10px;">
                            <div class="span5">
                                <div style="margin: 0 auto;text-align: justify;">{{article.text1|markdown}}</div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom:10px;text-align: justify;">
                            <div class="span5 hidden-phone">
                                <center>
                                    <div id="sklikReklama_468"></div>
                                    <script type="text/javascript">
                                        var sklikData = { elm: "sklikReklama_468", zoneId: 44368, w: 468, h: 80 };
                                    </script>
                                    <script type="text/javascript" src="http://c.imedia.cz/js/script.js"></script>
                                </center>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom:10px;">
                            <div class="span5">
                                <div style="margin: 0 auto;">{{article.text2|markdown}}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom:10px;"> <!-- GALLERY -->
                    <div class="span6">
                        <div class="row gallery">
                            {% if  article.img1 %}
                            <div class="span2" style="margin-bottom:10px;">
                                <a href="{{article.img1.url}}"><img src="{{article.img1.url}}" alt="{{article.img1_description}}"></a>
                                <p style="font-size: 0.8em">{{article.img1_description}} {{article.img1_author}}</p>
                            </div>
                            {% endif %}
                            {% if  article.img2 %}
                            <div class="span2" style="margin-bottom:10px;">
                                <a href="{{article.img2.url}}"><img src="{{article.img2.url}}" alt="{{article.img2_description}}"></a>
                                <p style="font-size: 0.8em">{{article.img2_description}} {{article.img2_author}}</p>
                            </div>
                            {% endif %}
                            {% if  article.img3 %}
                            <div class="span2" style="margin-bottom:10px;">
                                <a href="{{article.img3.url}}"><img src="{{article.img3.url}}" alt="{{article.img3_description}}"></a>
                                <p style="font-size: 0.8em">{{article.img3_description}} {{article.img3_author}}</p>
                            </div>
                            {% endif %}
                            {% if  article.img4 %}
                            <div class="span2" style="margin-bottom:10px;">
                                <a href="{{article.img4.url}}"><img src="{{article.img4.url}}" alt="{{article.img4_description}}"></a>
                                <p style="font-size: 0.8em">{{article.img4_description}} {{article.img4_author}}</p>
                            </div>
                            {% endif %}
                            {% if  article.img5 %}
                            <div class="span2" style="margin-bottom:10px;">
                                <a href="{{article.img5.url}}"><img src="{{article.img5.url}}" alt="{{article.img5_description}}"></a>
                                <p style="font-size: 0.8em">{{article.img5_description}} {{article.img5_author}}</p>
                            </div>
                            {% endif %}
                            {% if  article.img6 %}
                            <div class="span2" style="margin-bottom:10px;">
                                <a href="{{article.img6.url}}"><img src="{{article.img6.url}}" alt="{{article.img6_description}}"></a>
                                <p style="font-size: 0.8em">{{article.img6_description}} {{article.img6_author}}</p>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom:10px;">
                    <div class="span7">
                        <div class="row">
                            <div class="span">
                                <div id="fb-root"></div>
                                <script src="http://connect.facebook.net/cs_CZ/all.js#appId=218617268163634&amp;xfbml=1"></script><fb:like href="http://vozickarskenoviny.cz{% url "vn.article" article.url_key %}" send="false" layout="box_count" width="90" show_faces="false" action="recommend" font="arial"></fb:like>
                            </div>
                            <div class="span">
                                <a href="http://twitter.com/share" class="twitter-share-button" data-count="vertical" data-via="vozickarskenov" data-url="http://vozickarskenoviny.cz{% url "vn.article" article.url_key %}">Tweet</a>
                                <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
                            </div>
                            <div class="span">
                                <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
                                <g:plusone size="tall" href="http://vozickarskenoviny.cz{% url "vn.article" article.url_key %}"></g:plusone>
                            </div>
                        </div>
                        <!--  -->
                        {% include "vozickarskenoviny/comments.html" %}
                        <!--  -->
                    </div>
                </div>
            </div>
            <div class="span5" style="">
                <div class="row">
                    <div class="span5">
                        <h4>Další články z rubriky</h4>
                    </div>
                </div>
                {% for obj in related1 %}
                <div class="row" style="margin-bottom:10px;">
                    <div class="span2">
                        <a href="{% url "vn.article" obj.url_key %}"><img src="{{obj.img.url}}"></a>
                    </div>
                    <div class="span3">
                        <h3><a href="{% url "vn.article" obj.url_key %}">{{obj.title}}</a></h3>
                        <p style="font-size: 0.7em">
                            {% if obj.show_actualization %}
                                Poslední aktualizace:
                            {% else %}
                                Publikováno:
                            {% endif %}
                            {% if obj.show_actualization %}
                                {{ obj.date_actualization }}
                            {% else %}
                                {{ obj.date_creation }}
                            {% endif %}
                        </p>
                        <p>{{obj.perex}}</p>
                    </div>
                </div>
                {% endfor %}
                <div class="row" style="margin-bottom:10px;">
                    <div class="span5">
                        <p class="rek">{{ad.text1.text|safe}}</p>
                        <p class="rek">{{ad.text2.text|safe}}</p>
                        <div id="sklikReklama_0" class="hidden-phone"></div>
                        <script type="text/javascript">
                            var sklikData = { elm: "sklikReklama_0", zoneId: 44620, w: 200, h: 400 };
                        </script>
                        <script type="text/javascript" src="http://c.imedia.cz/js/script.js"></script>
                        <p class="rek">{{ad.text3.text|safe}}</p>
                        <p class="rek">{{ad.text4.text|safe}}</p>
                    </div>
                </div>
                {% for obj in related2 %}
                <div class="row" style="margin-bottom:10px;">
                    <div class="span2">
                        <a href="{% url "vn.article" obj.url_key %}"><img src="{{obj.img.url}}"></a>
                    </div>
                    <div class="span3">
                        <h3><a href="{% url "vn.article" obj.url_key %}">{{obj.title}}</a></h3>
                        <p style="font-size: 0.7em">
                            {% if obj.show_actualization %}
                                Poslední aktualizace:
                            {% else %}
                                Publikováno:
                            {% endif %}
                            {% if obj.show_actualization %}
                                {{ obj.date_actualization }}
                            {% else %}
                                {{ obj.date_creation }}
                            {% endif %}
                        </p>
                        <p>{{obj.perex}}</p>
                    </div>
                </div>
                {% endfor %}
                <div class="row" style="margin-bottom:10px;">
                    <div class="span5">
                        <!--<img src="/static/static/vozickarskenoviny/img/234x60.gif" class="rek">-->
                    </div>
                </div>
                {% for obj in related3 %}
                <div class="row" style="margin-bottom:10px;">
                    <div class="span2">
                        <a href="{% url "vn.article" obj.url_key %}"><img src="{{obj.img.url}}"></a>
                    </div>
                    <div class="span3">
                        <h3><a href="{% url "vn.article" obj.url_key %}">{{obj.title}}</a></h3>
                        <p style="font-size: 0.7em">
                            {% if obj.show_actualization %}
                                Poslední aktualizace:
                            {% else %}
                                Publikováno:
                            {% endif %}
                            {% if obj.show_actualization %}
                                {{ obj.date_actualization }}
                            {% else %}
                                {{ obj.date_creation }}
                            {% endif %}
                        </p>
                        <p>{{obj.perex}}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock base_content %}

vozickarskenoviny/templates/vozickarskenoviny/comments.html
<h3 id="comments">Comments</h3>
{% if not article.get_comments %}
    <p>Žádné komentáře.</p>
{% endif %}
{% for comment in article.get_comments %}
    <div class="row">
        <div class="span">
            <h4>{{comment.title}}</h4>
            <p>Autor: <b>{{comment.author_name}}</b> | {{comment.created_at}}</p>
            <p>{{comment.text|linebreaksbr}}</p>
        </div>
    </div>
{% endfor %}
<h3>Přidat komentář</h3>
<form action="" method="post">
{% csrf_token %}
<div class="row">
    <div class="span">
        <input id="id_author_name" type="text" name="author_name" maxlength="64" placeholder="* Jméno" />
    </div>
    <div class="span">
        <input id="id_author_email" type="text" name="author_email" maxlength="64" placeholder="* Email (nebude zobrazen)"/>
    </div>
</div>
<div class="row">
    <div class="span">
        <input id="id_title" type="text" name="title" maxlength="255" class="span7" placeholder="* Titulek"/>
    </div>
</div>
<div class="row">
    <div class="span">
        <textarea id="id_text" rows="5" cols="40" name="text" class="span7" placeholder="Text komwntáře"></textarea>
    </div>
</div>
<div class="row">
    <div class="span">
        <input type="submit" value="Odeslat komentář">
    </div>
</div>
</form>

vozickarskenoviny/templates/vozickarskenoviny/home.html
{% extends "vozickarskenoviny/base.html"%}
{% load simple_ads %}
{% block base_content %}
<div class="row"  style="margin-bottom:10px;">
    <div class="span7" style="">
        {% if last.video %}
            <iframe width="640px" height="480px" src="https://www.youtube.com/embed/{{ last.video }}" frameborder="0" allowfullscreen></iframe>
        {% else %}
            <a href="{% url "vn.article" last.url_key %}"><img src="{{last.img.url}}"></a>
        {% endif %}
        {% if last.img_description or last.img_author %}
            <p style="font-size: 0.8em; margin: 0;">
                {{last.img_description}} {{last.img_author}}
            </p>
        {% endif %}
    </div>
    <div class="span5" style="">
        <a href="{% url "vn.article" last.url_key %}"><h2>{{last.title}}</h2></a>
        <p style="font-size: 0.7em">
             {% if last.show_actualization %}
                Poslední aktualizace:
            {% else %}
                Publikováno:
            {% endif %}
            {% if last.show_actualization %}
                {{ last.date_actualization }}
            {% else %}
                {{ last.date_creation }}
            {% endif %}
        </p>
        <p>{{last.perex}}</p>
        <p class="readmore"><a href="{% url "vn.article" last.url_key %}">Číst dále</a></p>
        <div class="hidden-phone">
        {% random_ad_by_size '468x60' %}
        <br>
        {% random_ad_by_size '468x60' %}
        <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- 468x60 -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:468px;height:60px"
             data-ad-client="ca-pub-4678736864038715"
             data-ad-slot="4731750585"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
        </div>
        <!-- <p class="rek">Reklama</p>
        <p class="rek">Reklama</p>
        <center><img src="/static/static/vozickarskenoviny/img/234x60.gif" class="rek"></center>
        <p class="rek">Reklama</p>
        <p class="rek">Reklama</p> -->
    </div>
</div>
<div class="row">
    <div class="span9">
        <div class="row">
            <div class="span9" style="margin-bottom:10px;">
                <h4>Nejnovější články</h4>
            </div>
        </div>
        <div class="row">
            {% for obj in last3 %}
                <div class="span3" style="">
                    <a href="{% url "vn.article" obj.url_key %}"><img src="{{obj.img.url}}"></a>
                    <a href="{% url "vn.article" obj.url_key %}"><h3>{{obj.title}}</h3></a>
                    <p style="font-size: 0.7em">
                         {% if obj.show_actualization %}
                            Poslední aktualizace:
                        {% else %}
                            Publikováno:
                        {% endif %}
                        {% if obj.show_actualization %}
                            {{ obj.date_actualization }}
                        {% else %}
                            {{ obj.date_creation }}
                        {% endif %}
                    </p>
                    <p>{{obj.perex}}</p>
                    <p class="readmore"><a href="{% url "vn.article" obj.url_key %}">Číst dále</a></p>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="span3" style="">
        <!-- <img src="/static/static/vozickarskenoviny/img/240x400.gif"> -->
        <div id="sklikReklama_4462"></div>
        <script type="text/javascript">
            var sklikData = { elm: "sklikReklama_4462", zoneId: 44620, w: 200, h: 400 };
        </script>
        <script type="text/javascript" src="http://c.imedia.cz/js/script.js"></script>
    </div>
</div>
<div class="row" style="margin-bottom:10px;">
    <div class="span12">
        {% for line in last_from_section %}
            <div class="row">
                {% for obj in line %}
                    <div class="span6">
                    <div class="row" style="margin-bottom:10px;">
                        <div class="span6">
                            <a href="{% url "vn.section" obj.url_key %}" class="header-link"><h4>{{obj.name}}</h4></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span2">
                            <a href="{% url "vn.article" obj.last.url_key %}"><img src="{{obj.last.img.url}}"></a>
                        </div>
                        <div class="span4">
                            <a href="{% url "vn.article" obj.last.url_key %}"><h3>{{obj.last.title}}</h3></a>
                            <p style="font-size: 0.7em">
                                 {% if obj.last.show_actualization %}
                                    Poslední aktualizace:
                                {% else %}
                                    Publikováno:
                                {% endif %}
                                {% if obj.last.show_actualization %}
                                    {{ obj.last.date_actualization }}
                                {% else %}
                                    {{ obj.last.date_creation }}
                                {% endif %}
                            </p>
                            <p style="min-height: 60px">{{obj.last.perex}}</p>
                            <p class="readmore"><a href="{% url "vn.article" obj.last.url_key %}">Číst dále</a></p>
                        </div>
                    </div>
                    {% if obj.last1 %}
                    <div class="row">
                        <div class="span2">
                            <a href="{% url "vn.article" obj.last1.url_key %}"><img src="{{obj.last1.img.url}}"></a>
                        </div>
                        <div class="span4">
                            <a href="{% url "vn.article" obj.last1.url_key %}"><h3>{{obj.last1.title}}</h3></a>
                            <p style="font-size: 0.7em">
                                 {% if obj.last1.show_actualization %}
                                    Poslední aktualizace:
                                {% else %}
                                    Publikováno:
                                {% endif %}
                                {% if obj.last1.show_actualization %}
                                    {{ obj.last1.date_actualization }}
                                {% else %}
                                    {{ obj.last1.date_creation }}
                                {% endif %}
                            </p>
                            <p style="min-height: 60px">{{obj.last1.perex}}</p>
                            <p class="readmore"><a href="{% url "vn.article" obj.last1.url_key %}">Číst dále</a></p>
                        </div>
                    </div>
                    {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock base_content %}